sudo: required
language: generic

services:
  - docker

before_install:
  #container for testing is built using the dev Dockerfile
  - docker build -t sidrrao/react-test -f ./client/Dockerfile.dev ./client
    #tests for other containers can also be added here

script:
  - docker run -e CI=true sidrrao/react-test npm test #-- --coverage

after_success:
  - docker build -t sidrrao/multi-client ./client
  - docker build -t sidrrao/multi-nginx ./nginx
  - docker build -t sidrrao/multi-server ./server
  - docker build -t sidrrao/multi-worker ./worker
  #Login to the Docker CLI - docker login id and password are stored in Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push the images into Dockerhub
  - docker push sidrrao/multi-client
  - docker push sidrrao/multi-nginx
  - docker push sidrrao/multi-server
  - docker push sidrrao/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" 
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-649066511304"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY